### ISSUE TITLE
neoforge 1.21.1 .65 model issues?

### ISSUE THREAD

**Issue by VaporeonScripts** [Xylonity/Knight-Quest#2] opened 2024-10-02 14:05 UTC
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice_1' referenced from: knightquest:block/great_chalice_2: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice_1.json
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice_2' referenced from: knightquest:block/great_chalice_3: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice_2.json
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice_0' referenced from: knightquest:block/great_chalice: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice_0.json
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice' referenced from: knightquest:block/great_chalice_1: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice.json
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice_5' referenced from: knightquest:block/great_chalice_6: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice_5.json
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice_6' referenced from: knightquest:block/great_chalice_7: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice_6.json
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice_3' referenced from: knightquest:block/great_chalice_4: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice_3.json
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice_4' referenced from: knightquest:block/great_chalice_5: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice_4.json
[15:58:50] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:knight_quest_chalice_7' referenced from: knightquest:block/great_chalice_8: java.io.FileNotFoundException: minecraft:models/knight_quest_chalice_7.json

**Comment by VaporeonScripts** [comment] 2024-10-02 14:05
https://mclo.gs/7iCHiK6

**Comment by Xylonity** [comment] 2024-10-02 14:20
That's weird (maybe just a false-positive), the chalice model works as intended

**Comment by Xylonity** [comment] 2024-10-03 21:52
The code has been refractored and the great chalice is no longer part of this mod. Anyway, it has been fixed in Knight Lib.

**Closed as completed by Xylonity** 2024-10-03 21:52 UTC
Labels: bug

**Comment by VaporeonScripts** [comment] 2024-10-04 05:12
ig ima wait for knight quest neoforge release
